transform:
  - target: resource.aws_s3_bucket.main
    value:
      bucket: "${input.project_name}-bucket"
      tags:
        Environment: "${input.environment}"
        Project: "${input.project_name}"

  # Zweiter Zugriff auf das GLEICHE tiefere Map-Target:
  - target: resource.aws_s3_bucket.main
    value:
      tags:
        ManagedBy: "WattTF"