name: Pull Request CI

on:
  pull_request:
    branches: 
      - main
  push:
    branches:
      - main
  
jobs:
  lint:
    uses: devsebastianops/github-workflows/.github/workflows/lint.yaml@v1.0.0
    secrets: inherit
  e2e:
    uses: devsebastianops/github-workflows/.github/workflows/test.yaml@v1.0.0
    secrets: inherit
  test-install-script:
    uses: devsebastianops/github-workflows/.github/workflows/test-install-script.yaml@v1.0.0
    secrets: inherit
    with:
      binary: "wtf"