name: Release CD

permissions:
  contents: write
  pages: write
  id-token: write

on:
  release:
    types: [published]

jobs:
  docker:
    uses: devsebastianops/github-workflows/.github/workflows/release-docker.yaml@v1.0.0
    secrets: inherit
    with:
      binary: "wtf"

  go:
    uses: devsebastianops/github-workflows/.github/workflows/release-go.yaml@v1.0.0
    secrets: inherit
    with:
      binary: "wtf"
      

  github-pages:
    uses: devsebastianops/github-workflows/.github/workflows/release-github-pages.yaml@v1.0.0
    secrets: inherit