name: Relase Go Binaries

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  go:
    name: Release Go Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v7

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version-file: 'go.mod'
        cache-dependency-path: 'go.sum'
    
    - name: Install dependencies
      run: go mod download

    - name: Get tag version
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Build binary
      id: build
      run: |
        BINARY_NAME="wtf"
        if [ "${{ matrix.goos }}" = "windows" ]; then
          BINARY_NAME+=".exe"
        fi

        echo "binary_name=$BINARY_NAME" >> "$GITHUB_OUTPUT"

        CGO_ENABLED=0 GOOS="${{ matrix.goos }}" GOARCH="${{ matrix.goarch }}" go build -ldflags="-s -w" -o "$BINARY_NAME" ./cmd/wtf/main.go

    - name: Package binary
      id: package
      env:
        BINARY_NAME: ${{ steps.build.outputs.binary_name }}
      run: |
        ARCHIVE_NAME="wtf-${{ matrix.goos }}-${{ matrix.goarch }}-${{ steps.get_version.outputs.VERSION }}"
        if [ "${{ matrix.goos }}" = "windows" ]; then
          ARCHIVE_NAME+=".zip"
          zip -r "$ARCHIVE_NAME" "$BINARY_NAME"
        else
          ARCHIVE_NAME+=".tar.gz"
          tar -czf "$ARCHIVE_NAME" "$BINARY_NAME"
        fi
        
        echo "archive_name=$ARCHIVE_NAME" >> "$GITHUB_OUTPUT"

    - name: Update GitHub Release
      uses: softprops/action-gh-release@v3
      with:
        files: ${{ steps.package.outputs.archive_name }}